package com.example.straffic.config;

import com.example.straffic.dashboard.entity.PageViewHistoryEntity;
import com.example.straffic.dashboard.repository.PageViewHistoryRepository;
import lombok.RequiredArgsConstructor;
import org.springframework.boot.CommandLineRunner;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.stereotype.Component;

import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.LocalTime;
import java.util.ArrayList;
import java.util.List;
import java.util.Random;

@Component
@RequiredArgsConstructor
public class DataSeeder implements CommandLineRunner {

    private final PageViewHistoryRepository pageViewHistoryRepository;
    private final JdbcTemplate jdbcTemplate;
    private final Random random = new Random();

    @Override
    public void run(String... args) throws Exception {
        // 테이블 존재 여부 확인 및 생성
        try {
            Integer count = jdbcTemplate.queryForObject(
                "SELECT count(*) FROM user_tables WHERE table_name = 'PAGE_VIEW_HISTORY'", Integer.class);
            
            if (count != null && count == 0) {
                System.out.println("Creating table PAGE_VIEW_HISTORY...");
                
                try {
                    // Try Oracle 12c+ IDENTITY syntax first
                    jdbcTemplate.execute("""
                        CREATE TABLE page_view_history (
                            id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                            page_name VARCHAR2(255) NOT NULL,
                            viewed_at TIMESTAMP NOT NULL
                        )
                    """);
                    System.out.println("Table PAGE_VIEW_HISTORY created (12c+ syntax).");
                } catch (Exception e) {
                    System.out.println("12c syntax failed, trying 11g syntax (Sequence + Trigger)...");
                    // Fallback to Oracle 11g syntax
                    jdbcTemplate.execute("""
                        CREATE TABLE page_view_history (
                            id NUMBER PRIMARY KEY,
                            page_name VARCHAR2(255) NOT NULL,
                            viewed_at TIMESTAMP NOT NULL
                        )
                    """);
                    
                    // Create Sequence
                    try {
                        jdbcTemplate.execute("CREATE SEQUENCE page_view_history_seq START WITH 1 INCREMENT BY 1");
                    } catch (Exception ignored) {} // Sequence might exist
                    
                    // Create Trigger
                    jdbcTemplate.execute("""
                        CREATE OR REPLACE TRIGGER page_view_history_trg
                        BEFORE INSERT ON page_view_history
                        FOR EACH ROW
                        BEGIN
                            SELECT page_view_history_seq.NEXTVAL INTO :new.id FROM dual;
                        END;
                    """);
                    System.out.println("Table PAGE_VIEW_HISTORY created (11g syntax).");
                }
            }
        } catch (Exception e) {
            System.err.println("Error checking/creating table: " + e.getMessage());
            // If table creation failed, stop execution to prevent ORA-00942 in deleteAll()
            throw e;
        }

        // 기존 데이터 삭제 (항상 최신 상태 유지)
        pageViewHistoryRepository.deleteAll();
        System.out.println("Existing page view history deleted.");

        List<PageViewHistoryEntity> entities = new ArrayList<>();

        // 1. 2025년 데이터 (작년) - 약 1200개
        LocalDate start2025 = LocalDate.of(2025, 1, 1);
        for (int i = 0; i < 1200; i++) {
            PageViewHistoryEntity entity = new PageViewHistoryEntity();
            entity.setPageName(getRandomPageName());
            // 2025년 내 랜덤 날짜/시간
            entity.setViewedAt(getRandomDateTime(start2025, 365));
            entities.add(entity);
        }

        // 2. 이번 주 데이터 (2026-01-19 ~ 2026-01-25)
        // 월요일 (50개)
        addDailyData(entities, LocalDate.of(2026, 1, 19), 50);
        // 화요일 (80개)
        addDailyData(entities, LocalDate.of(2026, 1, 20), 80);
        // 수요일 (120개)
        addDailyData(entities, LocalDate.of(2026, 1, 21), 120);
        // 목요일 (오늘, 180개)
        addDailyData(entities, LocalDate.of(2026, 1, 22), 180);
        // 금요일 (250개)
        addDailyData(entities, LocalDate.of(2026, 1, 23), 250);
        // 토요일 (350개)
        addDailyData(entities, LocalDate.of(2026, 1, 24), 350);
        // 일요일 (500개)
        addDailyData(entities, LocalDate.of(2026, 1, 25), 500);

        // 일괄 저장
        pageViewHistoryRepository.saveAll(entities);
        System.out.println("DataSeeder: " + entities.size() + " records inserted.");
    }

    private void addDailyData(List<PageViewHistoryEntity> entities, LocalDate date, int count) {
        for (int i = 0; i < count; i++) {
            PageViewHistoryEntity entity = new PageViewHistoryEntity();
            entity.setPageName(getRandomPageName());
            entity.setViewedAt(getRandomTimeOnDate(date));
            entities.add(entity);
        }
    }

    private String getRandomPageName() {
        int r = random.nextInt(100);
        if (r < 25) return "PARKING";
        if (r < 50) return "KTX";
        if (r < 75) return "BIKE";
        return "SUBWAY";
    }

    private LocalDateTime getRandomDateTime(LocalDate startDate, int daysRange) {
        return startDate.plusDays(random.nextInt(daysRange))
                .atTime(LocalTime.of(random.nextInt(24), random.nextInt(60)));
    }

    private LocalDateTime getRandomTimeOnDate(LocalDate date) {
        return date.atTime(LocalTime.of(random.nextInt(24), random.nextInt(60)));
    }
}
